### PR TITLE
Test

### PR DESCRIPTION
**Pull request by elect86**
Hi James,

something like this..

I filled some missing methods like the constructor `Vec3(float f)` and created a copy of others to allows users who need to take allocation under control to pass directly the result (actually at the moment I don't need it, but I see there is a lot of people who cares about..)

So everybody uses what he prefer using the same one library

What do you think? :)

Ps: sorry for the whole file appearing to got deleted, I am used usually to format code while working, if it is a problem I can undo it

This was just a quick test, but if you like it and I get green light, I will implement all of these: 

- [this](https://github.com/elect86/jogl-samples/blob/master/jogl-samples/src/framework/Glm.java) 
- [this](https://github.com/elect86/jgli/blob/master/src/main/java/jgli/Glm.java)

### CODE REVIEW

**Comment by jroyalty** [comment]
Looks like your editor changed the tabs in that file.  Could you make the tab stops match the original file and resubmit the diff?

**Comment by elect86** [comment]
Done

**Comment by jroyalty** [comment]
First off, thanks for changing the formatting.  Second, did you add a `set()` method to Vec3 or its parent?  I see you calling it but I don't see it defined.  Regardless, having a method to mutate the state of the vector is against the principle of this whole library -- that the data classes are immutable.  E.g., every time you change something about a vector it's a new object.

So, as is, I can't accept this patch.  Plus, you need to add a few unit tests for the new functionality.

**Comment by elect86** [comment]
You are welcome..

I forgot to add it back, sorry, it is a way to copy one Vec3 in another one quick and without the need to instantiate a new class..

Which is the reason for the immutability?

**Comment by jroyalty** [comment]
The immutability was design decision to make these objects out-of-the-box thread safe.  The JVM is really good at creating many small objects that are short-lived -- like these objects.

**Comment by jroyalty** [comment]
Closing this.

If you'd like to take the `set()` method out and submit again I'll be happy to review it.

**Pull request closed without merging**
